################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
ASM_SRCS += \
../DSP_op.asm \
../convolve_asm.asm \
../deemph_asm.asm \
../divs.asm \
../gpclip_asm.asm \
../oper_32b_asm.asm \
../pit_shrp_asm.asm \
../preemph_asm.asm \
../residu_asm.asm \
../scale_asm.asm \
../updt_tar_asm.asm \
../util_asm.asm \
../wb_vad_asm.asm \
../weight_a_asm.asm 

C_SRCS += \
../agc2.c \
../az_isp.c \
../basicop2.c \
../bits.c \
../c2t64fx.c \
../c4t64fx.c \
../cod_main.c \
../common.c \
../convolve.c \
../cor_h_x.c \
../d2t64fx.c \
../d4t64fx.c \
../d_gain2.c \
../dec_main.c \
../decim54.c \
../deemph.c \
../divul.c \
../dtx.c \
../g_pitch.c \
../gpclip.c \
../homing.c \
../hp400.c \
../hp50.c \
../hp6k.c \
../hp7k.c \
../hp_wsp.c \
../int_lpc.c \
../isfextrp.c \
../isp_az.c \
../isp_isf.c \
../lag_wind.c \
../lagconc.c \
../levinson.c \
../lp_dec2.c \
../math_op.c \
../oper_32b.c \
../p_med_ol.c \
../ph_disp.c \
../pit_shrp.c \
../pitch_f4.c \
../pred_lt4.c \
../preemph.c \
../q_gain2.c \
../q_pulse.c \
../qisf_ns.c \
../qpisf_2s.c \
../residu.c \
../scale.c \
../syn_filt.c \
../updt_tar.c \
../util.c \
../voicefac.c \
../wb_vad.c \
../weight_a.c 

OBJS += \
./DSP_op.obj \
./agc2.obj \
./az_isp.obj \
./basicop2.obj \
./bits.obj \
./c2t64fx.obj \
./c4t64fx.obj \
./cod_main.obj \
./common.obj \
./convolve.obj \
./convolve_asm.obj \
./cor_h_x.obj \
./d2t64fx.obj \
./d4t64fx.obj \
./d_gain2.obj \
./dec_main.obj \
./decim54.obj \
./deemph.obj \
./deemph_asm.obj \
./divs.obj \
./divul.obj \
./dtx.obj \
./g_pitch.obj \
./gpclip.obj \
./gpclip_asm.obj \
./homing.obj \
./hp400.obj \
./hp50.obj \
./hp6k.obj \
./hp7k.obj \
./hp_wsp.obj \
./int_lpc.obj \
./isfextrp.obj \
./isp_az.obj \
./isp_isf.obj \
./lag_wind.obj \
./lagconc.obj \
./levinson.obj \
./lp_dec2.obj \
./math_op.obj \
./oper_32b.obj \
./oper_32b_asm.obj \
./p_med_ol.obj \
./ph_disp.obj \
./pit_shrp.obj \
./pit_shrp_asm.obj \
./pitch_f4.obj \
./pred_lt4.obj \
./preemph.obj \
./preemph_asm.obj \
./q_gain2.obj \
./q_pulse.obj \
./qisf_ns.obj \
./qpisf_2s.obj \
./residu.obj \
./residu_asm.obj \
./scale.obj \
./scale_asm.obj \
./syn_filt.obj \
./updt_tar.obj \
./updt_tar_asm.obj \
./util.obj \
./util_asm.obj \
./voicefac.obj \
./wb_vad.obj \
./wb_vad_asm.obj \
./weight_a.obj \
./weight_a_asm.obj 

ASM_DEPS += \
./DSP_op.pp \
./convolve_asm.pp \
./deemph_asm.pp \
./divs.pp \
./gpclip_asm.pp \
./oper_32b_asm.pp \
./pit_shrp_asm.pp \
./preemph_asm.pp \
./residu_asm.pp \
./scale_asm.pp \
./updt_tar_asm.pp \
./util_asm.pp \
./wb_vad_asm.pp \
./weight_a_asm.pp 

C_DEPS += \
./agc2.pp \
./az_isp.pp \
./basicop2.pp \
./bits.pp \
./c2t64fx.pp \
./c4t64fx.pp \
./cod_main.pp \
./common.pp \
./convolve.pp \
./cor_h_x.pp \
./d2t64fx.pp \
./d4t64fx.pp \
./d_gain2.pp \
./dec_main.pp \
./decim54.pp \
./deemph.pp \
./divul.pp \
./dtx.pp \
./g_pitch.pp \
./gpclip.pp \
./homing.pp \
./hp400.pp \
./hp50.pp \
./hp6k.pp \
./hp7k.pp \
./hp_wsp.pp \
./int_lpc.pp \
./isfextrp.pp \
./isp_az.pp \
./isp_isf.pp \
./lag_wind.pp \
./lagconc.pp \
./levinson.pp \
./lp_dec2.pp \
./math_op.pp \
./oper_32b.pp \
./p_med_ol.pp \
./ph_disp.pp \
./pit_shrp.pp \
./pitch_f4.pp \
./pred_lt4.pp \
./preemph.pp \
./q_gain2.pp \
./q_pulse.pp \
./qisf_ns.pp \
./qpisf_2s.pp \
./residu.pp \
./scale.pp \
./syn_filt.pp \
./updt_tar.pp \
./util.pp \
./voicefac.pp \
./wb_vad.pp \
./weight_a.pp 

C_DEPS__QUOTED += \
"agc2.pp" \
"az_isp.pp" \
"basicop2.pp" \
"bits.pp" \
"c2t64fx.pp" \
"c4t64fx.pp" \
"cod_main.pp" \
"common.pp" \
"convolve.pp" \
"cor_h_x.pp" \
"d2t64fx.pp" \
"d4t64fx.pp" \
"d_gain2.pp" \
"dec_main.pp" \
"decim54.pp" \
"deemph.pp" \
"divul.pp" \
"dtx.pp" \
"g_pitch.pp" \
"gpclip.pp" \
"homing.pp" \
"hp400.pp" \
"hp50.pp" \
"hp6k.pp" \
"hp7k.pp" \
"hp_wsp.pp" \
"int_lpc.pp" \
"isfextrp.pp" \
"isp_az.pp" \
"isp_isf.pp" \
"lag_wind.pp" \
"lagconc.pp" \
"levinson.pp" \
"lp_dec2.pp" \
"math_op.pp" \
"oper_32b.pp" \
"p_med_ol.pp" \
"ph_disp.pp" \
"pit_shrp.pp" \
"pitch_f4.pp" \
"pred_lt4.pp" \
"preemph.pp" \
"q_gain2.pp" \
"q_pulse.pp" \
"qisf_ns.pp" \
"qpisf_2s.pp" \
"residu.pp" \
"scale.pp" \
"syn_filt.pp" \
"updt_tar.pp" \
"util.pp" \
"voicefac.pp" \
"wb_vad.pp" \
"weight_a.pp" 

OBJS__QUOTED += \
"DSP_op.obj" \
"agc2.obj" \
"az_isp.obj" \
"basicop2.obj" \
"bits.obj" \
"c2t64fx.obj" \
"c4t64fx.obj" \
"cod_main.obj" \
"common.obj" \
"convolve.obj" \
"convolve_asm.obj" \
"cor_h_x.obj" \
"d2t64fx.obj" \
"d4t64fx.obj" \
"d_gain2.obj" \
"dec_main.obj" \
"decim54.obj" \
"deemph.obj" \
"deemph_asm.obj" \
"divs.obj" \
"divul.obj" \
"dtx.obj" \
"g_pitch.obj" \
"gpclip.obj" \
"gpclip_asm.obj" \
"homing.obj" \
"hp400.obj" \
"hp50.obj" \
"hp6k.obj" \
"hp7k.obj" \
"hp_wsp.obj" \
"int_lpc.obj" \
"isfextrp.obj" \
"isp_az.obj" \
"isp_isf.obj" \
"lag_wind.obj" \
"lagconc.obj" \
"levinson.obj" \
"lp_dec2.obj" \
"math_op.obj" \
"oper_32b.obj" \
"oper_32b_asm.obj" \
"p_med_ol.obj" \
"ph_disp.obj" \
"pit_shrp.obj" \
"pit_shrp_asm.obj" \
"pitch_f4.obj" \
"pred_lt4.obj" \
"preemph.obj" \
"preemph_asm.obj" \
"q_gain2.obj" \
"q_pulse.obj" \
"qisf_ns.obj" \
"qpisf_2s.obj" \
"residu.obj" \
"residu_asm.obj" \
"scale.obj" \
"scale_asm.obj" \
"syn_filt.obj" \
"updt_tar.obj" \
"updt_tar_asm.obj" \
"util.obj" \
"util_asm.obj" \
"voicefac.obj" \
"wb_vad.obj" \
"wb_vad_asm.obj" \
"weight_a.obj" \
"weight_a_asm.obj" 

ASM_DEPS__QUOTED += \
"DSP_op.pp" \
"convolve_asm.pp" \
"deemph_asm.pp" \
"divs.pp" \
"gpclip_asm.pp" \
"oper_32b_asm.pp" \
"pit_shrp_asm.pp" \
"preemph_asm.pp" \
"residu_asm.pp" \
"scale_asm.pp" \
"updt_tar_asm.pp" \
"util_asm.pp" \
"wb_vad_asm.pp" \
"weight_a_asm.pp" 

ASM_SRCS__QUOTED += \
"../DSP_op.asm" \
"../convolve_asm.asm" \
"../deemph_asm.asm" \
"../divs.asm" \
"../gpclip_asm.asm" \
"../oper_32b_asm.asm" \
"../pit_shrp_asm.asm" \
"../preemph_asm.asm" \
"../residu_asm.asm" \
"../scale_asm.asm" \
"../updt_tar_asm.asm" \
"../util_asm.asm" \
"../wb_vad_asm.asm" \
"../weight_a_asm.asm" 

C_SRCS__QUOTED += \
"../agc2.c" \
"../az_isp.c" \
"../basicop2.c" \
"../bits.c" \
"../c2t64fx.c" \
"../c4t64fx.c" \
"../cod_main.c" \
"../common.c" \
"../convolve.c" \
"../cor_h_x.c" \
"../d2t64fx.c" \
"../d4t64fx.c" \
"../d_gain2.c" \
"../dec_main.c" \
"../decim54.c" \
"../deemph.c" \
"../divul.c" \
"../dtx.c" \
"../g_pitch.c" \
"../gpclip.c" \
"../homing.c" \
"../hp400.c" \
"../hp50.c" \
"../hp6k.c" \
"../hp7k.c" \
"../hp_wsp.c" \
"../int_lpc.c" \
"../isfextrp.c" \
"../isp_az.c" \
"../isp_isf.c" \
"../lag_wind.c" \
"../lagconc.c" \
"../levinson.c" \
"../lp_dec2.c" \
"../math_op.c" \
"../oper_32b.c" \
"../p_med_ol.c" \
"../ph_disp.c" \
"../pit_shrp.c" \
"../pitch_f4.c" \
"../pred_lt4.c" \
"../preemph.c" \
"../q_gain2.c" \
"../q_pulse.c" \
"../qisf_ns.c" \
"../qpisf_2s.c" \
"../residu.c" \
"../scale.c" \
"../syn_filt.c" \
"../updt_tar.c" \
"../util.c" \
"../voicefac.c" \
"../wb_vad.c" \
"../weight_a.c" 


